# Generated by Django 5.0 on 2024-03-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('actors', models.TextField()),
                ('trailer_link', models.URLField()),
                ('img', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
